- backend/static/js/helper.js
With ad-freiburg/qlever#790 qlever will be returning metadata about parse errors. When a parsing error happens the exact location that caused it will also be returned. This PR makes use of that information in the frontend to highlight the location in the echoed query. The highlighting is still basic but it works. 
Example:
> Highlight tokens causing parse error if metadata available

- backend/static/js/helper.js
This PR enables the `Automatically add names to result` option for a knowledge graph that contains the VVZ (Vorlesungsverzeichnis) data. This has to be a PR because this cannot be configured in the Django. It is possible to make the knowledge graph available via qlever.cs.uni-freiburg.de once it is finished.
> Make "Automatically add names to result" checkbox work for `api/vvz`

- backend/static/css/style.css
- backend/static/js/helper.js
- backend/static/js/qleverUI.js
The runtime information shown in the "Analysis" tree now contains additional information, notably such related to "lazy index scans", see PR https://github.com/ad-freiburg/qlever/pull/1003 .
The status of the "normal" operations has been renamed to "fully materialized" and is not explicitly shown in the tree. The status of the lazy index scans is called "lazily materialized".
When hovering over a node in the tree, more detailed infomation is shown at the bottom if available.
> Show information about "lazy scans" in "Analysis" view

- backend/management/commands/examples.py
- backend/static/css/style.css
- backend/static/js/helper.js
- backend/static/js/qleverUI.js
- backend/urls.py
- backend/views.py
There is now a new command and view that can be used to retrieve all
example queries for a given backend as TSV. Here is an example call:
`docker exec -it qlever-ui bash -c "python manage.py examples wikidata"`
To obtain the same result via an API call (no special permissions
required):
`curl -s https://qlever.cs.uni-freiburg.de/api/examples/wikidata`
> Examples command

- backend/static/css/style.css
- backend/static/js/codemirror/modes/sparql/sparql-hint.js
- backend/static/js/helper.js
- backend/static/js/qleverUI.js
- backend/templates/index.html
So far, the "Analysis" button for a query showed the query execution tree *after* the query processing finished (and also if it failed). Now the tree is shown as soon as the query planning is done and the information in the operation nodes is updated live after each operation. The communication is realized via web sockets. On the side of the QLever backend, the corresponding changes in the code were made in https://github.com/ad-freiburg/qlever/pull/1119 .
> "Analysis" tree now shows live updates

- backend/static/js/helper.js
In the file `backernd/static/js/helper.js` the line `link = cpy.match(/(https?:\/\/[a-zA-Z0-9.:%/#\?_-]+)/g)[0];` led to issues with results of the `encode_for_uri` function (see https://github.com/ad-freiburg/qlever/pull/1128), because of a missing check if the `.match()` function actually finds any result.
> Fix bug when showing links in the result table

- backend/static/js/codemirror/modes/sparql/sparql-hint.js
- backend/static/js/codemirror/modes/sparql/sparql.js
1. Add documentation to `sparql-hint.js` and `sparql.js` (mostly the
former) to better understand what is going on.
2. In context-insensitive mode, make the object AC queries
half-sensitive, that is, take the predicate into account
3. Improve suggestions for variable names, e.g., a predicate `hasAuthor`
now leads to the suggestion of an object variable `?author`
> Add documentation and minor changes

- backend/static/js/helper.js
- backend/static/js/qleverUI.js
1. Improve rewriting for `FILTER KEYWORDS` (was previously called
`FILTER CONTAINS`, but this now collides with the built-in function
`CONTAINS`, which has been implemented for QLever in the meantime).
2. Improve code for pretty-printing the entries of the result table
(it's still somewhat hacky and, above all, inefficient, but that's
not new and work for another PR).
3. Show the `Map view` button also for the dblp-related instances.
> Improve filter keywords pretty printing etc

- backend/static/js/codemirror/modes/sparql/sparql-hint.js
- backend/static/js/qleverUI.js
For a while now, the TTL files on https://osm2rdf.cs.uni-freiburg.de provide the geometry WKTs via `geo:hasGeometry/geo:asWKT` (because that is how it should be according to the GeoSPARQL standard), and not directly via `geo:hasGeometry` as it used to be.
To ease query construction, the QLever UI now automagically suggests `geo:hasGeometry/geo:asWKT` whenever `geo:hasGeometry` is among the suggested predicates. We had a similar mechanism already for predicates like `wdt:P31` (in which case also `wdt:P31/wdt:P279*` is suggested).
When `geo:hasGeometry/geo:asWKT` is selected by the user, the variable name suggestion is `?geometry` and not `?as_wkt`.
On the side, also show the Map view button for OHM (when the result contains geometries in the last column, as usual).
> Suggest geo:hasGeometry/geo:asWKT automagically

- docs/install_qleverui.md
The `Dockerfile` and `Makefile` both use the port `7000`, but the documentation mentioned a different port. This is now fixed.
> Update docs to use port `7000`, as in `Dockerfile` and `Makefile`

- backend/static/js/codemirror/modes/sparql/sparql-hint.js
- backend/static/js/codemirror/modes/sparql/sparql.js
- backend/static/js/helper.js
- backend/static/js/qleverUI.js
Some of the useful automatic features of the query editor went rogue under certain conditions. Three things are now fixed or at least better:
1. When the query did not contain `SELECT` in all upper case and one of the existing prefixes was typed, each cursor movement would be followed by a reversal of that movement, which made the UI unusable. This is now fixed. In particular, this fixes #57.
2. So far, the query was "cleaned up" (blank lines removed, whitespace replaced by single spaces, etc.) after *every* cursor movement, which was not always desired. Now the query is only cleaned up in this way when the `TAB` key is pressed (which jumps between the different positions in the placeholder). In particular, this fixes #63.
3. Some REGEXes were only looking for a fully uppercase version of …
> Fix wild behavior when `SELECT` is missing + other improvements in this vein

- backend/static/js/codemirror/modes/sparql/sparql-hint.js
Without typing at least a few characters, it's more confusing than helpful to suggest a subject AC query to the user. It is currently hard-coded that at least 3 characters have to be typed, but this should be a configurable parameter.
> No subject AC query for short prefix

- backend/static/css/style.css
- backend/static/js/qleverUI.js
This PR changes the way `details` are displayed in the query planning tree.
| before | after |
|-----------|---------|
| ![before](https://github.com/ad-freiburg/qlever-ui/assets/74186504/0016e2f9-8140-4599-a682-764211fc11b7)| ![after](https://github.com/ad-freiburg/qlever-ui/assets/74186504/0b7b2745-889b-4624-8f92-510699de031d)|
This is done with `tooltips`
There are two issues i ran into, both seem to come from the combination of `Treant.js` and `popper.js`.
When the tooltip is outside of the Treant canvas, it just gets cut off.
To solve this i place the tooltip below the node if the y-position is below 20px.
That's a hack, but it seems to work fine.
| issue | fix |
|---------|-----|
| ![clipping-issue](https://github.com/ad-freiburg/qlever-ui/assets/74186504/fc5298a0-076a-4dbc-ac27-e8c2 …
> Display details for operation in "Analysis" tree as tooltip

- .github/workflows/docker-publish.yml
- Dockerfile
So far, Docker images were build and pushed to Docker Hub irregularly by Hannah. Now there is a GitHub action for this, which run after each commit to the master. Also, unlike before, these are now multiarch builds (for `linux/amd64` and `linux/arm64`). Addresses #96
> Build and push Docker image after each commit to the master

- Dockerfile
- qlever/settings.py
So far, the variable for static storage in `settings.py` was called `STATICFILES_STORAGE`. Since Django 4.2, this is deprecated and now part of a dict called `STORAGES`.  See https://docs.djangoproject.com/en/5.1/ref/settings/#storages
> Update deprecated setting for static storage

- .dockerignore
We ignore this for our local image because there we mount the `db` directory as a volume. But for the Docker build and push action, it should of course not be ignored. This should fix #99
> Don't ignore `db` when building Docker image

- backend/management/commands/prefixes.py
- backend/models.py
- backend/urls.py
- backend/views.py
The new command can be called in two ways (taking `wikdata` as example backend config):
python manage.py prefixes wikidata  [possibly within Docker]
curl -s https://qlever.cs.uni-freiburg.de/api/prefixes/wikidata
In both cases, the output is a text with all the prefix definitions defined for the requests backend, with one definition per line, using `PREFIX` (and not `@prefix`) and without trailing dot, sorted alphabetically. For example, for Wikidata:
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX data: <https://www.wikidata.org/wiki/Special:EntityData/>
PREFIX dct: <http://purl.org/dc/terms/>
...
PREFIX wdtn: <http://www.wikidata.org/prop/direct-normalized/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
On the side, reformat some …
> Add command `prefixes` to obtain prefix definitions from backend config

- backend/static/js/helper.js
Allow comments of the form `#!TEMPLATE PLACEHOLDER=VALUE` in queries. The effect is that all occurrences of `%PLACEHOLDER%` in the query are replaced by `VALUE`. Very simple and useful
> Templated queries via `#!TEMPLATE PLACEHOLDER=VALUE` comment

- backend/static/js/qleverUI.js
- backend/templates/partials/modals/share.html
For SELECT queries, request media type `application/sparql-results+json` for POST queries and `application/qlever-results+json` for POST queries. For CONSTRUCT queries, request media type `text/turtle` for both.
> In `Share` dialog, have separate lines for GET and POST

- backend/static/js/qleverUI.js
- backend/templates/partials/head.html
- formatter/index.js
- package-lock.json
- package.json
PR #126 introduced an automatic detection whether the operation is `query` or `update`. This was done via regexes and not correct in all cases. This is now fixed by using `qlue-ls` for parsing (and defaulting to type `query` when the parser could not determine the type).
Resolves #137. Resolves #138. Resolves ad-freiburg/qlever#1838. Resolves #140.
> Fix operation type detection

- package-lock.json
- package.json
In particular, this fixes the wrong formatting for `CONSTRUCT WHERE { ... }` queries.
> Bump `qlue-ls` version to `0.5.3`

- backend/static/js/helper.js
- backend/static/js/qleverUI.js
For multiple updates, this shows aggregated statistics (also saying how many updates were aggregated). The query response used to be a JSON object and is now an array of JSON objects. For "Analysis", the last update in a chain is shown.
This should be merged before ad-freiburg/qlever#1883, which implemented chained updates in QLever.
> Support chained updates in the UI

- backend/static/css/style.css
- backend/static/js/qleverUI.js
- backend/templates/index.html
When a string is entered in the "Access Token" field in the "Backend Information" panel, two buttons for privileged commands appear (one for removing all delta triples and one for clearing the cache completely, including the pinned results). So far, these buttons appeared in the same "Backend Information" panel, which is usually hidden. Now they appear in the row below the usual buttons (for executing the query, downloading the result, etc).
> Show buttons for privileged commands in main panel

- backend/management/commands/config.py
So far, the YAML exported or imported by the `config` command contained values for both `id` and `slug` under `backend`. Indeed, both of these are part of the `Backend` model. If the values for these differed between the YAML and the database, an error was reported. However, this made it challenging to exchange such YAML files between different users.
We now consider the `id` an implementation detail that should neither be exported nor imported. Indeed, an error is now reported if the YAML file contains an `id` key under `backend`. Only the `slug` key is used to identify the backend in the database.
NOTE: For historical reasons, the value of `slug` is not unique in the `Backend` model. It should be, but that is work for a separate PR (which will require a database migration).
> Remove key `id` from YAML file exported by `config` command

- backend/views.py
None of the information returned by the config API is really secret. Indeed, most of it could be obtained by interacting with the respective instance of the QLever UI (except for the `apiToken`, which, however, is a relic of the past and should be removed from the config altogether).
On the positive side, making this API public help users who want to set up their own QLever UI instance. In particular, they can now simply get a copy of the config of an existing instance and modify it to their own liking.
> Remove `@login_required` from calls to `config` API

- backend/static/js/qleverUI.js
For some reason `Treant.js` does not clean itself up automatically when you overwrite a previously rendered tree. This happens frequently for the "Analysis" tree when there are live updates. This change makes sure to explicitly call `destroy()` before the tree is re-rendered.
> Destroy `Treant.js` tree before re-rendering to avoid memory issues

- backend/static/js/qleverUI.js
- backend/views.py
Quotes `"` were already escaped, but backslashes `\` were not. This is now fixed
> Escape backslashes in queries for `Share` dialog

- package-lock.json
- package.json
In particular, this fixes that a query like `INSERT DATA { <a> <b> "'." }` was not recognized as an update operation.
> Bump `Qlue-ls` version to 0.15.0
